version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userdb

  tour-service:
    build: ./tour-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/tourdb

  review-service:
    build: ./review-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/reviewdb

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - tour-service
      - review-service

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
